version: '3.3'
services: 
    db:
        build: ./db
    server:
        build: . 
        ports: 
            - 3001:3001
        depends_on:
            - db
        restart: on-failure
        command: 
            yarn serve